/**
 * @file OutputWriter.hpp
 * @brief 输出写入器
 * 
 * 亚高山森林演替模型 (SFE-Model)
 * 
 * Phase 7 Task 7.3: 统计与输出
 * 
 * 输出格式：
 * - plot_year_summary.txt: 年度汇总（LAI、生物量、个体数）
 * - individual_tree_status.txt: 每棵树的详情
 * - species_composition.txt: 物种组成统计
 */

#ifndef SFE_OUTPUT_WRITER_HPP
#define SFE_OUTPUT_WRITER_HPP

#include <string>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <vector>
#include <map>
#include <set>
#include <filesystem>

#include "core/Types.hpp"
#include "entities/Plot.hpp"
#include "entities/AdultTree.hpp"
#include "entities/Sapling.hpp"
#include "simulation/SimulationController.hpp"

namespace sfe {

/**
 * @class OutputWriter
 * @brief 输出文件写入器
 */
class OutputWriter {
public:
    /**
     * @brief 构造函数
     * @param output_dir 输出目录
     */
    explicit OutputWriter(const std::string& output_dir = "./output/")
        : output_dir_(output_dir)
    {
        // 确保输出目录存在
        std::filesystem::create_directories(output_dir_);
    }
    
    /**
     * @brief 设置输出目录
     */
    void setOutputDir(const std::string& dir) {
        output_dir_ = dir;
        std::filesystem::create_directories(output_dir_);
    }
    
    // ========================================================================
    // 年度汇总输出
    // ========================================================================
    
    /**
     * @brief 写入年度汇总头部
     */
    void writeSummaryHeader() {
        std::string filepath = output_dir_ + "plot_year_summary.txt";
        std::ofstream ofs(filepath);
        
        ofs << "# Plot Year Summary\n";
        ofs << "# Generated by SFE-Model\n";
        ofs << "#\n";
        ofs << std::setw(6) << "Year" << "\t"
            << std::setw(8) << "PlotID" << "\t"
            << std::setw(8) << "Trees" << "\t"
            << std::setw(10) << "Saplings" << "\t"
            << std::setw(12) << "TreeBio_kg" << "\t"
            << std::setw(12) << "HerbBio_kg" << "\t"
            << std::setw(10) << "TotalBio" << "\t"
            << std::setw(8) << "TreeLAI" << "\t"
            << std::setw(8) << "HerbLAI" << "\t"
            << std::setw(8) << "TotalLAI" << "\t"
            << std::setw(6) << "GDD" << "\t"
            << std::setw(8) << "Precip" << "\t"
            << std::setw(6) << "DI" << "\t"
            << std::setw(8) << "NewSdl" << "\t"
            << std::setw(8) << "Recruit" << "\t"
            << std::setw(8) << "DeadTr" << "\t"
            << std::setw(6) << "Fire"
            << "\n";
        
        ofs.close();
        summary_initialized_ = true;
    }
    
    /**
     * @brief 追加年度统计
     */
    void appendSummary(const YearlyStats& stats) {
        if (!summary_initialized_) {
            writeSummaryHeader();
        }
        
        std::string filepath = output_dir_ + "plot_year_summary.txt";
        std::ofstream ofs(filepath, std::ios::app);
        
        ofs << std::fixed << std::setprecision(2);
        ofs << std::setw(6) << stats.year << "\t"
            << std::setw(8) << stats.plot_id << "\t"
            << std::setw(8) << stats.tree_count << "\t"
            << std::setw(10) << stats.sapling_count << "\t"
            << std::setw(12) << stats.tree_biomass_kg << "\t"
            << std::setw(12) << stats.herb_biomass_kg << "\t"
            << std::setw(10) << stats.total_biomass_kg << "\t"
            << std::setw(8) << stats.tree_lai << "\t"
            << std::setw(8) << stats.herb_lai << "\t"
            << std::setw(8) << stats.total_lai << "\t"
            << std::setw(6) << static_cast<int>(stats.annual_gdd) << "\t"
            << std::setw(8) << stats.annual_precip << "\t"
            << std::setw(6) << stats.annual_drought_index << "\t"
            << std::setw(8) << stats.new_seedlings << "\t"
            << std::setw(8) << stats.recruited_trees << "\t"
            << std::setw(8) << stats.dead_trees << "\t"
            << std::setw(6) << (stats.fire_occurred ? 1 : 0)
            << "\n";
        
        ofs.close();
    }
    
    // ========================================================================
    // 个体树木状态输出
    // ========================================================================
    
    /**
     * @brief 写入个体树木状态
     * @param plots 所有样方
     * @param year 当前年份
     */
    void writeIndividualTrees(const std::vector<Plot>& plots, int year) {
        std::string filepath = output_dir_ + "individual_tree_status_" + 
                               std::to_string(year) + ".txt";
        std::ofstream ofs(filepath);
        
        ofs << "# Individual Tree Status - Year " << year << "\n";
        ofs << "# Generated by SFE-Model\n";
        ofs << "#\n";
        ofs << std::setw(8) << "PlotID" << "\t"
            << std::setw(8) << "TreeID" << "\t"
            << std::setw(10) << "SpeciesID" << "\t"
            << std::setw(8) << "X_m" << "\t"
            << std::setw(8) << "Y_m" << "\t"
            << std::setw(10) << "DBH_cm" << "\t"
            << std::setw(10) << "Height_m" << "\t"
            << std::setw(6) << "Age" << "\t"
            << std::setw(10) << "LeafArea" << "\t"
            << std::setw(10) << "CrownRad" << "\t"
            << std::setw(8) << "Light" << "\t"
            << std::setw(8) << "Stress"
            << "\n";
        
        ofs << std::fixed << std::setprecision(3);
        
        for (const auto& plot : plots) {
            PlotId plot_id = plot.getPlotId();
            
            for (const auto& tree : plot.getTrees()) {
                if (!tree.isAlive()) continue;
                
                ofs << std::setw(8) << plot_id << "\t"
                    << std::setw(8) << tree.getId() << "\t"
                    << std::setw(10) << tree.getSpeciesId() << "\t"
                    << std::setw(8) << tree.getX() << "\t"
                    << std::setw(8) << tree.getY() << "\t"
                    << std::setw(10) << tree.getDbh() << "\t"
                    << std::setw(10) << tree.getHeight() << "\t"
                    << std::setw(6) << tree.getAge() << "\t"
                    << std::setw(10) << tree.getLeafArea() << "\t"
                    << std::setw(10) << tree.getCrownRadius() << "\t"
                    << std::setw(8) << tree.getAvailableLight() << "\t"
                    << std::setw(8) << tree.getStressYears()
                    << "\n";
            }
        }
        
        ofs.close();
    }
    
    /**
     * @brief 写入个体幼树状态
     */
    void writeIndividualSaplings(const std::vector<Plot>& plots, int year) {
        std::string filepath = output_dir_ + "individual_sapling_status_" + 
                               std::to_string(year) + ".txt";
        std::ofstream ofs(filepath);
        
        ofs << "# Individual Sapling Status - Year " << year << "\n";
        ofs << "# Generated by SFE-Model\n";
        ofs << "#\n";
        ofs << std::setw(8) << "PlotID" << "\t"
            << std::setw(10) << "SaplingID" << "\t"
            << std::setw(10) << "SpeciesID" << "\t"
            << std::setw(8) << "X_m" << "\t"
            << std::setw(8) << "Y_m" << "\t"
            << std::setw(10) << "Height_m" << "\t"
            << std::setw(6) << "Age" << "\t"
            << std::setw(8) << "Stress"
            << "\n";
        
        ofs << std::fixed << std::setprecision(3);
        
        for (const auto& plot : plots) {
            PlotId plot_id = plot.getPlotId();
            
            for (const auto& sapling : plot.getSaplings()) {
                if (!sapling.isAlive()) continue;
                
                ofs << std::setw(8) << plot_id << "\t"
                    << std::setw(10) << sapling.getId() << "\t"
                    << std::setw(10) << sapling.getSpeciesId() << "\t"
                    << std::setw(8) << sapling.getX() << "\t"
                    << std::setw(8) << sapling.getY() << "\t"
                    << std::setw(10) << sapling.getHeight() << "\t"
                    << std::setw(6) << sapling.getAge() << "\t"
                    << std::setw(8) << sapling.getStressYears()
                    << "\n";
            }
        }
        
        ofs.close();
    }
    
    // ========================================================================
    // 物种组成输出
    // ========================================================================
    
    /**
     * @brief 写入物种组成统计
     */
    void writeSpeciesComposition(const std::vector<Plot>& plots, int year) {
        std::string filepath = output_dir_ + "species_composition_" + 
                               std::to_string(year) + ".txt";
        std::ofstream ofs(filepath);
        
        ofs << "# Species Composition - Year " << year << "\n";
        ofs << "# Generated by SFE-Model\n";
        ofs << "#\n";
        ofs << std::setw(8) << "PlotID" << "\t"
            << std::setw(10) << "SpeciesID" << "\t"
            << std::setw(10) << "TreeCount" << "\t"
            << std::setw(12) << "SapCount" << "\t"
            << std::setw(12) << "BasalArea" << "\t"
            << std::setw(12) << "TotalLA" << "\t"
            << std::setw(12) << "MeanDBH" << "\t"
            << std::setw(12) << "MeanHeight"
            << "\n";
        
        ofs << std::fixed << std::setprecision(3);
        
        for (const auto& plot : plots) {
            PlotId plot_id = plot.getPlotId();
            
            // 按物种统计成树
            std::map<SpeciesId, std::vector<const AdultTree*>> trees_by_species;
            for (const auto& tree : plot.getTrees()) {
                if (tree.isAlive()) {
                    trees_by_species[tree.getSpeciesId()].push_back(&tree);
                }
            }
            
            // 按物种统计幼树
            std::map<SpeciesId, int> sapling_counts;
            for (const auto& sapling : plot.getSaplings()) {
                if (sapling.isAlive()) {
                    sapling_counts[sapling.getSpeciesId()]++;
                }
            }
            
            // 合并所有物种
            std::set<SpeciesId> all_species;
            for (const auto& [sp, _] : trees_by_species) all_species.insert(sp);
            for (const auto& [sp, _] : sapling_counts) all_species.insert(sp);
            
            for (SpeciesId sp : all_species) {
                int tree_count = 0;
                double basal_area = 0.0;
                double total_la = 0.0;
                double sum_dbh = 0.0;
                double sum_height = 0.0;
                
                if (trees_by_species.count(sp)) {
                    for (const auto* tree : trees_by_species[sp]) {
                        tree_count++;
                        double dbh_m = tree->getDbh() / 100.0;
                        basal_area += 3.1416 * dbh_m * dbh_m / 4.0;
                        total_la += tree->getLeafArea();
                        sum_dbh += tree->getDbh();
                        sum_height += tree->getHeight();
                    }
                }
                
                int sapling_count = sapling_counts.count(sp) ? sapling_counts[sp] : 0;
                double mean_dbh = tree_count > 0 ? sum_dbh / tree_count : 0.0;
                double mean_height = tree_count > 0 ? sum_height / tree_count : 0.0;
                
                ofs << std::setw(8) << plot_id << "\t"
                    << std::setw(10) << sp << "\t"
                    << std::setw(10) << tree_count << "\t"
                    << std::setw(12) << sapling_count << "\t"
                    << std::setw(12) << basal_area << "\t"
                    << std::setw(12) << total_la << "\t"
                    << std::setw(12) << mean_dbh << "\t"
                    << std::setw(12) << mean_height
                    << "\n";
            }
        }
        
        ofs.close();
    }
    
    // ========================================================================
    // 便捷方法
    // ========================================================================
    
    /**
     * @brief 写入所有输出（年度结束时调用）
     */
    void writeAllOutputs(const std::vector<Plot>& plots, 
                         const YearlyStats& stats,
                         int year) {
        appendSummary(stats);
        
        // 每年都写详细输出（可根据需要调整间隔）
        writeIndividualTrees(plots, year);
        writeIndividualSaplings(plots, year);
        writeSpeciesComposition(plots, year);
    }
    
    /**
     * @brief 生成简洁的控制台输出
     */
    static std::string formatConsoleOutput(const YearlyStats& stats) {
        std::ostringstream oss;
        oss << std::fixed << std::setprecision(1);
        oss << "Year " << stats.year 
            << " | Trees: " << stats.tree_count
            << " | Saplings: " << stats.sapling_count
            << " | LAI: " << stats.total_lai
            << " | Bio: " << stats.total_biomass_kg << " kg"
            << " | New: " << stats.new_seedlings
            << " | Dead: " << stats.dead_trees;
        if (stats.fire_occurred) {
            oss << " | FIRE";
        }
        return oss.str();
    }
    
private:
    std::string output_dir_;
    bool summary_initialized_ = false;
};

} // namespace sfe

#endif // SFE_OUTPUT_WRITER_HPP
